// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrfKI7SpbPwcPXhiu5sCxkEAPw0P4uaOI',
    appId: '1:641585197024:web:230af2d9bf185a08ba8585',
    messagingSenderId: '641585197024',
    projectId: 'cloud-task-1b4a3',
    authDomain: 'cloud-task-1b4a3.firebaseapp.com',
    storageBucket: 'cloud-task-1b4a3.appspot.com',
    measurementId: 'G-0QW3LDR939',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcf-_abPELNowhFlEdlQwx5uc4W334OsM',
    appId: '1:641585197024:android:be0ed3f003de3078ba8585',
    messagingSenderId: '641585197024',
    projectId: 'cloud-task-1b4a3',
    storageBucket: 'cloud-task-1b4a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVc10Wq9NcWsrH0ZPHI4TM0KnvVNeiDCY',
    appId: '1:641585197024:ios:59a6d1430359e2e0ba8585',
    messagingSenderId: '641585197024',
    projectId: 'cloud-task-1b4a3',
    storageBucket: 'cloud-task-1b4a3.appspot.com',
    iosBundleId: 'com.example.cloudTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVc10Wq9NcWsrH0ZPHI4TM0KnvVNeiDCY',
    appId: '1:641585197024:ios:ec2bf41138667802ba8585',
    messagingSenderId: '641585197024',
    projectId: 'cloud-task-1b4a3',
    storageBucket: 'cloud-task-1b4a3.appspot.com',
    iosBundleId: 'com.example.cloudTask.RunnerTests',
  );
}
